language: go
go:
  - "1.10"
sudo: false
before_install:
  - curl https://glide.sh/get | sh
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.13.2
install:
  - glide install
  - golangci-lint --version
script:
  - golangci-lint run ./...
  - go test ./... -race -short
